---
- name: Unzip Creatio archive
# 1.1 unzip -d /path/to/application/directory/ CREATIO_ARCHIVE_NAME.zip
  ansible.builtin.unarchive:
    src: "{{ creatio_archive_path }}"
    dest: "{{ creatio_installation_path }}"
  #  remote_src: true
  become: yes

# 1.2 Create ConnectionStrings.config file
# 1.2.1 Go to the root directory of the Creatio application and open
# if file exists - delete it
- name: Remove existing ConnectionStrings.config file if it exists
  ansible.builtin.file:
    path: "{{ creatio_installation_path }}/ConnectionStrings.config"
    state: absent
  when: creatio_installation_path is defined and creatio_installation_path != ""

- name: Create ConnectionStrings.config file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/ConnectionStrings.config.j2"
    dest: "{{ creatio_installation_path }}/ConnectionStrings.config"
    owner: gnet
    group: gnet
    mode: '0644'
  when: creatio_installation_path is defined and creatio_installation_path != ""

# build docker compose project
- name: Build Docker Compose project not run
  ansible.builtin.command:
    cmd: "docker compose -f {{ playbook_dir }}/docker-compose.yaml build"
  args:
    chdir: "{{ creatio_installation_path }}"
  register: docker_compose_output
  ignore_errors: yes



